notifications:
  email:
    - iceblade112@users.noreply.github.com
    - PyroSamurai@users.noreply.github.com
language: csharp
solution: TrickEmu.sln
install:
  - nuget restore TrickEmu.sln
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.5 TrickEmu.sln
